import React, { useEffect, useState } from 'react';
import Head from 'next/head'
import axios, { AxiosResponse } from 'axios';
import { Text, TableContainer, Table, TableCaption, Thead, Tbody, Tr, Th, Td } from '@chakra-ui/react';
import styles from '../styles/Home.module.css'

interface Activity {
  id: string;
  title: string;
  date: string;
  description: string;
  category: string;
  city: string;
  venue: string;
}

export default function Home() {
  const [activities, setActivities] = useState<Activity[]>([])

  useEffect(() => {
    axios.get('http://localhost:5000/api/activities').then((response: AxiosResponse<Activity[]>) => {
      setActivities(response.data);
    });
  }, []);

  return (
    <div className={ styles.container }>
      <Head>
        <title>Reactivities</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main className={ styles.main }>
        <Text fontSize="6xl">
          Activities
        </Text>
        <TableContainer>
          <Table variant='simple'>
            <TableCaption>Imperial to metric conversion factors</TableCaption>
            <Thead>
              <Tr>
                <Th>Title</Th>
                <Th>Date</Th>
                <Th>City</Th>
                <Th>Venue</Th>
              </Tr>
            </Thead>
            <Tbody>
              { activities.length === 0 ? (
                <Tr>
                  <Td colSpan={ 3 }>No activities</Td>
                </Tr>
              ) : activities.map((a) => (
                <Tr>
                  <Td>{ a.title }</Td>
                  <Td>{ a.date }</Td>
                  <Td>{ a.city }</Td>
                  <Td>{ a.venue }</Td>
                </Tr>
              )) }
            </Tbody>
          </Table>
        </TableContainer>
      </main>
    </div>
  );
}
